### ISSUE TITLE
tetration のバグ報告

### ISSUE THREAD

**Issue by rsk0315** [kopricky/my_algorithm#10]
https://github.com/kopricky/My-Algorithm/blob/d7e4d215a4b9e7b1a56823f52b87d382f647a3ce/Competitive_Programming/Computation_Advanced/tetration.hpp#L50-L55

2^^3 = 16 ですが、`tetration(2, 3, 32)` が `0` を返してしまいます

https://wandbox.org/permlink/645BTJINOI8CnGzh

**Comment by kopricky** [comment]
えびちゃんさん、バグ報告ありがとうございます！
mod_pow 内で res(途中結果) が mod 以上となったら flag を立てるようにしていたのですが  a * a >= mod となった時点で flag を true にしまってるのがマズそうです...

**Comment by kopricky** [comment]
https://github.com/kopricky/My-Algorithm/blob/d137e3961abf5433cde0420eb8b48bd342e6fbba/Competitive_Programming/Computation_Advanced/tetration.hpp#L29-L41
バグの修正とリファクタリングをしました。
今回のバグで不利益などありましたら申し訳ないです。

**Comment by rsk0315** [comment]
ありがとうございます。不利益とかは被っていないので大丈夫です〜
