### ISSUE TITLE
初期化リストの初期化順序

### ISSUE THREAD

**Issue by polyomino24** [kopricky/my_algorithm#3]
merge segtreeですが、AOJ2426Treasure Huntで以下のコードを提出するとRuntime errorで落ちます。
https://ideone.com/9TtdY3
手元ではgcc8では動きますがclangでは動きません(warningもでます)。
初期化リストの部分をsorted((int)cand.size())とするか、int szを他の変数より前に持ってくる必要があるそうです。
参考:https://qiita.com/tyanmahou/items/c8f69a1a23d2f7669cfc

**Comment by kopricky** [comment]
ありがとう！
なんとなく今まで基本的にはメンバ変数と初期化順序そろえてたけど絶対にそろえないとまずいのね
(他のコードも確認するわ)
