### ISSUE TITLE
tetrationのa=0の場合にバグがある

### ISSUE THREAD

**Issue by hotman78** [kopricky/my_algorithm#7]
https://kopricky.github.io/code/Computation_Advanced/tetration.html の記事において
https://judge.yosupo.jp/submission/1982 のverifyでWAが出てます

**Comment by kopricky** [comment]
ご報告ありがとうございます！ 修正しました。
加えて周期が始まる前かどうか(指数部が小さいかどうか) の処理部分を pow を用いて行なっていましたが別の方法に変更しました。
また記事の説明をだいぶ端折って書いていたのでもう少しちゃんと書きました。
