### ISSUE TITLE
C4 Find Algorithm　O(msqrt(m))

### ISSUE THREAD

**Issue by ianCK** [kopricky/my_algorithm#9]
これは O(msqrt(m)) でできます

説明：[CF comment](https://codeforces.ml/blog/entry/63729?#comment-477823)

verify 用の問題：

[CF 1468 M](https://codeforces.com/contest/1468/problem/M)

[CF gym 102028 L](https://codeforces.ml/gym/102028/problem/L)

**Comment by kopricky** [comment]
より強い C4 の Counting を O(m sqrt(m)) で行うアルゴリズムを https://kopricky.github.io/code/Graph/CountingC4.html に掲載しています(手法は紹介いただいた問題の解法と同様です).
O(n^2) 時間の C4 Find Algorithm は実装が簡単であり, また密グラフ(m = Θ(n^2)) の場合にはより高速になるという利点があります.
